// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtkhzvjqtvsayxiheeue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0a2h6dmpxdHZzYXl4aWhlZXVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDY5MTksImV4cCI6MjA2MDI4MjkxOX0.3kgjmO-03cUPj-ZeDbBh9065iHJunNG6c-oldSpjuS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);